<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/20 13:36:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'postgres:host=locahost;dbname=mdc;port=5432',
  'username' => 'postgres',
  'password' => 'ninguna',
  'name' => 'doctrine',
)),);
