<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/20 13:47:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=locahost;dbname=mdc;port=5432;',
  'username' => 'postgres',
  'password' => 'ninguna',
  'name' => 'doctrine',
)),);
